In [37]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [38]:
df = pd.read_csv("train.csv")
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [39]:
print(df.head())
print("***************************************************")
print(df.info())
print("***************************************************")
print(df.describe())

   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg
1   2          20       RL         80.0     9600   Pave   NaN      Reg
2   3          60       RL         68.0    11250   Pave   NaN      IR1
3   4          70       RL         60.0     9550   Pave   NaN      IR1
4   5          60       RL         84.0    14260   Pave   NaN      IR1

  LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0         Lvl    AllPub    Inside       Gtl      CollgCr       Norm
1         Lvl    AllPub       FR2       Gtl      Veenker      Feedr
2         Lvl    AllPub    Inside       Gtl      CollgCr       Norm
3         Lvl    AllPub    Corner       Gtl      Crawfor       Norm
4         Lvl    AllPub       FR2       Gtl      NoRidge       Norm

  Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0       Norm     1Fam     2Story            7            5       2003
1       Norm     1Fam     1Story            6            8       1976
2       Norm     1Fam     2Story            7            5       2001
3       Norm     1Fam     2Story            7            5       1915
4       Norm     1Fam     2Story            8            5       2000

   YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0          2003     Gable  CompShg     VinylSd     VinylSd    BrkFace
1          1976     Gable  CompShg     MetalSd     MetalSd        NaN
2          2002     Gable  CompShg     VinylSd     VinylSd    BrkFace
3          1970     Gable  CompShg     Wd Sdng     Wd Shng        NaN
4          2000     Gable  CompShg     VinylSd     VinylSd    BrkFace

   MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure  \
0       196.0        Gd        TA      PConc       Gd       TA           No
1         0.0        TA        TA     CBlock       Gd       TA           Gd
2       162.0        Gd        TA      PConc       Gd       TA           Mn
3         0.0        TA        TA     BrkTil       TA       Gd           No
4       350.0        Gd        TA      PConc       Gd       TA           Av

  BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
0          GLQ         706          Unf           0        150          856
1          ALQ         978          Unf           0        284         1262
2          GLQ         486          Unf           0        434          920
3          ALQ         216          Unf           0        540          756
4          GLQ         655          Unf           0        490         1145

  Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  \
0    GasA        Ex          Y      SBrkr       856       854             0
1    GasA        Ex          Y      SBrkr      1262         0             0
2    GasA        Ex          Y      SBrkr       920       866             0
3    GasA        Gd          Y      SBrkr       961       756             0
4    GasA        Ex          Y      SBrkr      1145      1053             0

   GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  \
0       1710             1             0         2         1             3
1       1262             0             1         2         0             3
2       1786             1             0         2         1             3
3       1717             1             0         1         0             3
4       2198             1             0         2         1             4

   KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu  \
0             1          Gd             8        Typ           0         NaN
1             1          TA             6        Typ           1          TA
2             1          Gd             6        Typ           1          TA
3             1          Gd             7        Typ           1          Gd
4             1          Gd             9        Typ           1          TA

  GarageType  GarageYrBlt GarageFinish  GarageCars  GarageArea GarageQual  \
0     Attchd       2003.0          RFn           2         548         TA
1     Attchd       1976.0          RFn           2         460         TA
2     Attchd       2001.0          RFn           2         608         TA
3     Detchd       1998.0          Unf           3         642         TA
4     Attchd       2000.0          RFn           3         836         TA

  GarageCond PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  \
0         TA          Y           0           61              0          0
1         TA          Y         298            0              0          0
2         TA          Y           0           42              0          0
3         TA          Y           0           35            272          0
4         TA          Y         192           84              0          0

   ScreenPorch  PoolArea PoolQC Fence MiscFeature  MiscVal  MoSold  YrSold  \
0            0         0    NaN   NaN         NaN        0       2    2008
1            0         0    NaN   NaN         NaN        0       5    2007
2            0         0    NaN   NaN         NaN        0       9    2008
3            0         0    NaN   NaN         NaN        0       2    2006
4            0         0    NaN   NaN         NaN        0      12    2008

  SaleType SaleCondition  SalePrice
0       WD        Normal     208500
1       WD        Normal     181500
2       WD        Normal     223500
3       WD       Abnorml     140000
4       WD        Normal     250000
***************************************************
<class 'pandas.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   str
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   str
 6   Alley          91 non-null     str
 7   LotShape       1460 non-null   str
 8   LandContour    1460 non-null   str
 9   Utilities      1460 non-null   str
 10  LotConfig      1460 non-null   str
 11  LandSlope      1460 non-null   str
 12  Neighborhood   1460 non-null   str
 13  Condition1     1460 non-null   str
 14  Condition2     1460 non-null   str
 15  BldgType       1460 non-null   str
 16  HouseStyle     1460 non-null   str
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   str
 22  RoofMatl       1460 non-null   str
 23  Exterior1st    1460 non-null   str
 24  Exterior2nd    1460 non-null   str
 25  MasVnrType     588 non-null    str
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   str
 28  ExterCond      1460 non-null   str
 29  Foundation     1460 non-null   str
 30  BsmtQual       1423 non-null   str
 31  BsmtCond       1423 non-null   str
 32  BsmtExposure   1422 non-null   str
 33  BsmtFinType1   1423 non-null   str
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   str
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   str
 40  HeatingQC      1460 non-null   str
 41  CentralAir     1460 non-null   str
 42  Electrical     1459 non-null   str
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   str
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   str
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    str
 58  GarageType     1379 non-null   str
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   str
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   str
 64  GarageCond     1379 non-null   str
 65  PavedDrive     1460 non-null   str
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      str
 73  Fence          281 non-null    str
 74  MiscFeature    54 non-null     str
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   str
 79  SaleCondition  1460 non-null   str
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), str(43)
memory usage: 924.0 KB
None
***************************************************
                Id   MSSubClass  LotFrontage        LotArea  OverallQual  \
count  1460.000000  1460.000000  1201.000000    1460.000000  1460.000000
mean    730.500000    56.897260    70.049958   10516.828082     6.099315
std     421.610009    42.300571    24.284752    9981.264932     1.382997
min       1.000000    20.000000    21.000000    1300.000000     1.000000
25%     365.750000    20.000000    59.000000    7553.500000     5.000000
50%     730.500000    50.000000    69.000000    9478.500000     6.000000
75%    1095.250000    70.000000    80.000000   11601.500000     7.000000
max    1460.000000   190.000000   313.000000  215245.000000    10.000000

       OverallCond    YearBuilt  YearRemodAdd   MasVnrArea   BsmtFinSF1  \
count  1460.000000  1460.000000   1460.000000  1452.000000  1460.000000
mean      5.575342  1971.267808   1984.865753   103.685262   443.639726
std       1.112799    30.202904     20.645407   181.066207   456.098091
min       1.000000  1872.000000   1950.000000     0.000000     0.000000
25%       5.000000  1954.000000   1967.000000     0.000000     0.000000
50%       5.000000  1973.000000   1994.000000     0.000000   383.500000
75%       6.000000  2000.000000   2004.000000   166.000000   712.250000
max       9.000000  2010.000000   2010.000000  1600.000000  5644.000000

        BsmtFinSF2    BsmtUnfSF  TotalBsmtSF     1stFlrSF     2ndFlrSF  \
count  1460.000000  1460.000000  1460.000000  1460.000000  1460.000000
mean     46.549315   567.240411  1057.429452  1162.626712   346.992466
std     161.319273   441.866955   438.705324   386.587738   436.528436
min       0.000000     0.000000     0.000000   334.000000     0.000000
25%       0.000000   223.000000   795.750000   882.000000     0.000000
50%       0.000000   477.500000   991.500000  1087.000000     0.000000
75%       0.000000   808.000000  1298.250000  1391.250000   728.000000
max    1474.000000  2336.000000  6110.000000  4692.000000  2065.000000

       LowQualFinSF    GrLivArea  BsmtFullBath  BsmtHalfBath     FullBath  \
count   1460.000000  1460.000000   1460.000000   1460.000000  1460.000000
mean       5.844521  1515.463699      0.425342      0.057534     1.565068
std       48.623081   525.480383      0.518911      0.238753     0.550916
min        0.000000   334.000000      0.000000      0.000000     0.000000
25%        0.000000  1129.500000      0.000000      0.000000     1.000000
50%        0.000000  1464.000000      0.000000      0.000000     2.000000
75%        0.000000  1776.750000      1.000000      0.000000     2.000000
max      572.000000  5642.000000      3.000000      2.000000     3.000000

          HalfBath  BedroomAbvGr  KitchenAbvGr  TotRmsAbvGrd   Fireplaces  \
count  1460.000000   1460.000000   1460.000000   1460.000000  1460.000000
mean      0.382877      2.866438      1.046575      6.517808     0.613014
std       0.502885      0.815778      0.220338      1.625393     0.644666
min       0.000000      0.000000      0.000000      2.000000     0.000000
25%       0.000000      2.000000      1.000000      5.000000     0.000000
50%       0.000000      3.000000      1.000000      6.000000     1.000000
75%       1.000000      3.000000      1.000000      7.000000     1.000000
max       2.000000      8.000000      3.000000     14.000000     3.000000

       GarageYrBlt   GarageCars   GarageArea   WoodDeckSF  OpenPorchSF  \
count  1379.000000  1460.000000  1460.000000  1460.000000  1460.000000
mean   1978.506164     1.767123   472.980137    94.244521    46.660274
std      24.689725     0.747315   213.804841   125.338794    66.256028
min    1900.000000     0.000000     0.000000     0.000000     0.000000
25%    1961.000000     1.000000   334.500000     0.000000     0.000000
50%    1980.000000     2.000000   480.000000     0.000000    25.000000
75%    2002.000000     2.000000   576.000000   168.000000    68.000000
max    2010.000000     4.000000  1418.000000   857.000000   547.000000

       EnclosedPorch    3SsnPorch  ScreenPorch     PoolArea       MiscVal  \
count    1460.000000  1460.000000  1460.000000  1460.000000   1460.000000
mean       21.954110     3.409589    15.060959     2.758904     43.489041
std        61.119149    29.317331    55.757415    40.177307    496.123024
min         0.000000     0.000000     0.000000     0.000000      0.000000
25%         0.000000     0.000000     0.000000     0.000000      0.000000
50%         0.000000     0.000000     0.000000     0.000000      0.000000
75%         0.000000     0.000000     0.000000     0.000000      0.000000
max       552.000000   508.000000   480.000000   738.000000  15500.000000

            MoSold       YrSold      SalePrice
count  1460.000000  1460.000000    1460.000000
mean      6.321918  2007.815753  180921.195890
std       2.703626     1.328095   79442.502883
min       1.000000  2006.000000   34900.000000
25%       5.000000  2007.000000  129975.000000
50%       6.000000  2008.000000  163000.000000
75%       8.000000  2009.000000  214000.000000
max      12.000000  2010.000000  755000.000000

In [40]:
print("Is Null:")
fields_with_null_values = df.isnull().sum()
fields_with_null_values = fields_with_null_values[fields_with_null_values > 0]

null_info = pd.DataFrame({
    'Missing Values': fields_with_null_values,
    'Data Type': df.dtypes[fields_with_null_values.index]
})

print(null_info)

Is Null:
              Missing Values Data Type
LotFrontage              259   float64
Alley                   1369       str
MasVnrType               872       str
MasVnrArea                 8   float64
BsmtQual                  37       str
BsmtCond                  37       str
BsmtExposure              38       str
BsmtFinType1              37       str
BsmtFinType2              38       str
Electrical                 1       str
FireplaceQu              690       str
GarageType                81       str
GarageYrBlt               81   float64
GarageFinish              81       str
GarageQual                81       str
GarageCond                81       str
PoolQC                  1453       str
Fence                   1179       str
MiscFeature             1406       str

In [41]:
df[df["MasVnrArea"].isnull()]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
234,235,60,RL,NaN,7851,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,2002,2002,Gable,CompShg,VinylSd,VinylSd,NaN,NaN,Gd,TA,PConc,Gd,TA,No,GLQ,625,Unf,0,235,860,GasA,Ex,Y,SBrkr,860,1100,0,1960,1,0,2,1,4,1,Gd,8,Typ,2,TA,BuiltIn,2002.0,Fin,2,440,TA,TA,Y,288,48,0,0,0,0,NaN,NaN,NaN,0,5,2010,WD,Normal,216500
529,530,20,RL,NaN,32668,Pave,NaN,IR1,Lvl,AllPub,CulDSac,Gtl,Crawfor,Norm,Norm,1Fam,1Story,6,3,1957,1975,Hip,CompShg,Wd Sdng,Stone,NaN,NaN,Gd,TA,PConc,TA,TA,No,Rec,1219,Unf,0,816,2035,GasA,TA,Y,SBrkr,2515,0,0,2515,1,0,3,0,4,2,TA,9,Maj1,2,TA,Attchd,1975.0,RFn,2,484,TA,TA,Y,0,0,200,0,0,0,NaN,NaN,NaN,0,3,2007,WD,Alloca,200624
650,651,60,FV,65.0,8125,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,1Fam,2Story,7,6,2007,2007,Gable,CompShg,CemntBd,CmentBd,NaN,NaN,Gd,TA,PConc,Gd,TA,No,Unf,0,Unf,0,813,813,GasA,Ex,Y,SBrkr,822,843,0,1665,0,0,2,1,3,1,Gd,7,Typ,0,NaN,Attchd,2007.0,RFn,2,562,TA,TA,Y,0,0,0,0,0,0,NaN,NaN,NaN,0,5,2008,WD,Normal,205950
936,937,20,RL,67.0,10083,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,SawyerW,Norm,Norm,1Fam,1Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,NaN,NaN,Gd,TA,PConc,Gd,TA,No,GLQ,833,Unf,0,343,1176,GasA,Ex,Y,SBrkr,1200,0,0,1200,1,0,2,0,2,1,Gd,5,Typ,0,NaN,Attchd,2003.0,RFn,2,555,TA,TA,Y,0,41,0,0,0,0,NaN,NaN,NaN,0,8,2009,WD,Normal,184900
973,974,20,FV,95.0,11639,Pave,NaN,Reg,Lvl,AllPub,Corner,Gtl,Somerst,Norm,Norm,1Fam,1Story,7,5,2007,2008,Gable,CompShg,CemntBd,CmentBd,NaN,NaN,Gd,TA,PConc,Gd,TA,No,Unf,0,Unf,0,1428,1428,GasA,Ex,Y,SBrkr,1428,0,0,1428,0,0,2,0,3,1,Gd,6,Typ,0,NaN,Attchd,2007.0,Fin,2,480,TA,TA,Y,0,120,0,0,0,0,NaN,NaN,NaN,0,12,2008,New,Partial,182000
977,978,120,FV,35.0,4274,Pave,Pave,IR1,Lvl,AllPub,Inside,Gtl,Somerst,Norm,Norm,TwnhsE,1Story,7,5,2006,2007,Gable,CompShg,VinylSd,VinylSd,NaN,NaN,Gd,TA,PConc,Gd,TA,No,GLQ,1106,Unf,0,135,1241,GasA,Ex,Y,SBrkr,1241,0,0,1241,1,0,1,1,1,1,Gd,4,Typ,0,NaN,Attchd,2007.0,Fin,2,569,TA,TA,Y,0,116,0,0,0,0,NaN,NaN,NaN,0,11,2007,New,Partial,199900
1243,1244,20,RL,107.0,13891,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NridgHt,Norm,Norm,1Fam,1Story,10,5,2006,2006,Gable,CompShg,VinylSd,VinylSd,NaN,NaN,Ex,TA,PConc,Ex,Gd,Gd,GLQ,1386,Unf,0,690,2076,GasA,Ex,Y,SBrkr,2076,0,0,2076,1,0,2,1,2,1,Ex,7,Typ,1,Gd,Attchd,2006.0,Fin,3,850,TA,TA,Y,216,229,0,0,0,0,NaN,NaN,NaN,0,9,2006,New,Partial,465000
1278,1279,60,RL,75.0,9473,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,8,5,2002,2002,Gable,CompShg,VinylSd,VinylSd,NaN,NaN,Gd,TA,PConc,Gd,TA,No,GLQ,804,Unf,0,324,1128,GasA,Ex,Y,SBrkr,1128,903,0,2031,1,0,2,1,3,1,Gd,7,Typ,1,Gd,Attchd,2002.0,RFn,2,577,TA,TA,Y,0,211,0,0,0,0,NaN,NaN,NaN,0,3,2008,WD,Normal,237000

In [42]:
df[df["Electrical"].isnull()]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1379,1380,80,RL,73.0,9735,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Timber,Norm,Norm,1Fam,SLvl,5,5,2006,2007,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,Unf,0,Unf,0,384,384,GasA,Gd,Y,NaN,754,640,0,1394,0,0,2,1,3,1,Gd,7,Typ,0,NaN,BuiltIn,2007.0,Fin,2,400,TA,TA,Y,100,0,0,0,0,0,NaN,NaN,NaN,0,5,2008,WD,Normal,167500

In [43]:
df["LotFrontage"] = (
    df.groupby("Neighborhood")["LotFrontage"]
      .transform(lambda x: x.fillna(x.median()))
)

df["Electrical"] = df["Electrical"].fillna(
    df["Electrical"].mode()[0]
)

df["Alley"] = df["Alley"].fillna("None")
df["MasVnrType"] = df["MasVnrType"].fillna("None")
df["MasVnrArea"] = df["MasVnrArea"].fillna(0)
df["BsmtQual"] = df["BsmtQual"].fillna("None")
df["BsmtCond"] = df["BsmtCond"].fillna("None")
df["BsmtExposure"] = df["BsmtExposure"].fillna("None")
df["BsmtFinType1"] = df["BsmtFinType1"].fillna("None")
df["BsmtFinType2"] = df["BsmtFinType2"].fillna("None")
df["FireplaceQu"] = df["FireplaceQu"].fillna("None")
df["GarageType"] = df["GarageType"].fillna("None")
df["GarageYrBlt"] = df["GarageYrBlt"].fillna(0)
df["GarageFinish"] = df["GarageFinish"].fillna("None")
df["GarageQual"] = df["GarageQual"].fillna("None")
df["GarageCond"] = df["GarageCond"].fillna("None")
df["PoolQC"] = df["PoolQC"].fillna("None")
df["Fence"] = df["Fence"].fillna("None")
df["MiscFeature"] = df["MiscFeature"].fillna("None")

Nominal Catagories:
"MSSubClass",
"MSZoning",
"Street",
"Alley",
"LotShape",
"LandContour",
"Utilities",
"LotConfig",
"LandSlope",
"Neighborhood",
"Condition1",
"Condition2",
"BldgType",
"HouseStyle",
"RoofStyle",
"RoofMatl",
"Exterior1st",
"Exterior2nd",
"MasVnrType",
"Foundation",
"Heating",
"Electrical",
"GarageType",
"Fence",
"MiscFeature",
"SaleType",
"SaleCondition"

Y/N:
"CentralAir"

Ordinal 1-10:
"OverallQual",
"OverallCond"

Ordinal Po-Ex(5):
"ExterQual",
"ExterCond",
"HeatingQC",
"KitchenQual"

Ordinal Na-Ex(6):
"BsmtQual",
"BsmtCond",
"FireplaceQu",
"GarageQual",
"GarageCond"

Ordinal Na-Ex(5):
"PoolQC"

Ordinal Misc:
"BsmtExposure",
"BsmtFinType1",
"BsmtFinType2",
"Functional",
"GarageFinish",
"PavedDrive"??

In [ ]:
# Nominal Map 
nominal_columns = [
"MSSubClass",
"MSZoning",
"Street",
"Alley",
"LotShape",
"LandContour",
"Utilities",
"LotConfig",
"LandSlope",
"Neighborhood",
"Condition1",
"Condition2",
"BldgType",
"HouseStyle",
"RoofStyle",
"RoofMatl",
"Exterior1st",
"Exterior2nd",
"MasVnrType",
"Foundation",
"Heating",
"Electrical",
"GarageType",
"Fence",
"MiscFeature",
"SaleType",
"SaleCondition"
]

df = pd.get_dummies(
  df,
  columns=nominal_columns,
drop_first=True
)

# Yes/No Map
quality_map = {
  "N": 0,
  "Y": 1
}

df["CentralAir"] = df["CentralAir"].map(quality_map)

# Poor - Excellent 5 Rankings Map
quality_map = {
  "Po": 0,
  "Fa": 1,
  "TA": 2,
  "Gd": 3,
  "Ex": 4
}

ordinal_po_ex_5 = [
"ExterQual",
"ExterCond",
"HeatingQC",
"KitchenQual"
]

for category in ordinal_po_ex_5:
  df[category]=df[category].map(quality_map)

# NA - Excellent 6 Rankings Map
quality_map = {
  "NA": 0,
  "Po": 1,
  "Fa": 2,
  "TA": 3,
  "Gd": 4,
  "Ex": 5
}

ordinal_na_ex_6 = [
"BsmtQual",
"BsmtCond",
"FireplaceQu",
"GarageQual",
"GarageCond"
]


# NA - Excellent 5 Rankings Map
quality_map = {
  "NA": 0,
  "Fa": 1,
  "TA": 2,
  "Gd": 3,
  "Ex": 4
}

ordinal_na_ex_5 = [
  "PoolQC"
]


# Misc. Ordinal Rankings Map

# "BsmtExposure"
# "BsmtFinType1"
# "BsmtFinType2"
# "Functional"
# "GarageFinish"
# "PavedDrive"

In [45]:
print(df.head())
print("***************************************************")
print(df.info())
print("***************************************************")
print(df.describe())

   Id  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0   1         65.0     8450            7            5       2003
1   2         80.0     9600            6            8       1976
2   3         68.0    11250            7            5       2001
3   4         60.0     9550            7            5       1915
4   5         84.0    14260            8            5       2000

   YearRemodAdd  MasVnrArea ExterQual ExterCond BsmtQual BsmtCond  \
0          2003       196.0        Gd        TA       Gd       TA
1          1976         0.0        TA        TA       Gd       TA
2          2002       162.0        Gd        TA       Gd       TA
3          1970         0.0        TA        TA       TA       Gd
4          2000       350.0        Gd        TA       Gd       TA

  BsmtExposure BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  \
0           No          GLQ         706          Unf           0        150
1           Gd          ALQ         978          Unf           0        284
2           Mn          GLQ         486          Unf           0        434
3           No          ALQ         216          Unf           0        540
4           Av          GLQ         655          Unf           0        490

   TotalBsmtSF HeatingQC  CentralAir  1stFlrSF  2ndFlrSF  LowQualFinSF  \
0          856        Ex           1       856       854             0
1         1262        Ex           1      1262         0             0
2          920        Ex           1       920       866             0
3          756        Gd           1       961       756             0
4         1145        Ex           1      1145      1053             0

   GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  \
0       1710             1             0         2         1             3
1       1262             0             1         2         0             3
2       1786             1             0         2         1             3
3       1717             1             0         1         0             3
4       2198             1             0         2         1             4

   KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu  \
0             1          Gd             8        Typ           0        None
1             1          TA             6        Typ           1          TA
2             1          Gd             6        Typ           1          TA
3             1          Gd             7        Typ           1          Gd
4             1          Gd             9        Typ           1          TA

   GarageYrBlt GarageFinish  GarageCars  GarageArea GarageQual GarageCond  \
0       2003.0          RFn           2         548         TA         TA
1       1976.0          RFn           2         460         TA         TA
2       2001.0          RFn           2         608         TA         TA
3       1998.0          Unf           3         642         TA         TA
4       2000.0          RFn           3         836         TA         TA

  PavedDrive  WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  \
0          Y           0           61              0          0            0
1          Y         298            0              0          0            0
2          Y           0           42              0          0            0
3          Y           0           35            272          0            0
4          Y         192           84              0          0            0

   PoolArea PoolQC  MiscVal  MoSold  YrSold  SalePrice  MSSubClass_30  \
0         0   None        0       2    2008     208500          False
1         0   None        0       5    2007     181500          False
2         0   None        0       9    2008     223500          False
3         0   None        0       2    2006     140000          False
4         0   None        0      12    2008     250000          False

   MSSubClass_40  MSSubClass_45  MSSubClass_50  MSSubClass_60  MSSubClass_70  \
0          False          False          False           True          False
1          False          False          False          False          False
2          False          False          False           True          False
3          False          False          False          False           True
4          False          False          False           True          False

   MSSubClass_75  MSSubClass_80  MSSubClass_85  MSSubClass_90  MSSubClass_120  \
0          False          False          False          False           False
1          False          False          False          False           False
2          False          False          False          False           False
3          False          False          False          False           False
4          False          False          False          False           False

   MSSubClass_160  MSSubClass_180  MSSubClass_190  MSZoning_FV  MSZoning_RH  \
0           False           False           False        False        False
1           False           False           False        False        False
2           False           False           False        False        False
3           False           False           False        False        False
4           False           False           False        False        False

   MSZoning_RL  MSZoning_RM  Street_Pave  Alley_None  Alley_Pave  \
0         True        False         True        True       False
1         True        False         True        True       False
2         True        False         True        True       False
3         True        False         True        True       False
4         True        False         True        True       False

   LotShape_IR2  LotShape_IR3  LotShape_Reg  LandContour_HLS  LandContour_Low  \
0         False         False          True            False            False
1         False         False          True            False            False
2         False         False         False            False            False
3         False         False         False            False            False
4         False         False         False            False            False

   LandContour_Lvl  Utilities_NoSeWa  LotConfig_CulDSac  LotConfig_FR2  \
0             True             False              False          False
1             True             False              False           True
2             True             False              False          False
3             True             False              False          False
4             True             False              False           True

   LotConfig_FR3  LotConfig_Inside  LandSlope_Mod  LandSlope_Sev  \
0          False              True          False          False
1          False             False          False          False
2          False              True          False          False
3          False             False          False          False
4          False             False          False          False

   Neighborhood_Blueste  Neighborhood_BrDale  Neighborhood_BrkSide  \
0                 False                False                 False
1                 False                False                 False
2                 False                False                 False
3                 False                False                 False
4                 False                False                 False

   Neighborhood_ClearCr  Neighborhood_CollgCr  Neighborhood_Crawfor  \
0                 False                  True                 False
1                 False                 False                 False
2                 False                  True                 False
3                 False                 False                  True
4                 False                 False                 False

   Neighborhood_Edwards  Neighborhood_Gilbert  Neighborhood_IDOTRR  \
0                 False                 False                False
1                 False                 False                False
2                 False                 False                False
3                 False                 False                False
4                 False                 False                False

   Neighborhood_MeadowV  Neighborhood_Mitchel  Neighborhood_NAmes  \
0                 False                 False               False
1                 False                 False               False
2                 False                 False               False
3                 False                 False               False
4                 False                 False               False

   Neighborhood_NPkVill  Neighborhood_NWAmes  Neighborhood_NoRidge  \
0                 False                False                 False
1                 False                False                 False
2                 False                False                 False
3                 False                False                 False
4                 False                False                  True

   Neighborhood_NridgHt  Neighborhood_OldTown  Neighborhood_SWISU  \
0                 False                 False               False
1                 False                 False               False
2                 False                 False               False
3                 False                 False               False
4                 False                 False               False

   Neighborhood_Sawyer  Neighborhood_SawyerW  Neighborhood_Somerst  \
0                False                 False                 False
1                False                 False                 False
2                False                 False                 False
3                False                 False                 False
4                False                 False                 False

   Neighborhood_StoneBr  Neighborhood_Timber  Neighborhood_Veenker  \
0                 False                False                 False
1                 False                False                  True
2                 False                False                 False
3                 False                False                 False
4                 False                False                 False

   Condition1_Feedr  Condition1_Norm  Condition1_PosA  Condition1_PosN  \
0             False             True            False            False
1              True            False            False            False
2             False             True            False            False
3             False             True            False            False
4             False             True            False            False

   Condition1_RRAe  Condition1_RRAn  Condition1_RRNe  Condition1_RRNn  \
0            False            False            False            False
1            False            False            False            False
2            False            False            False            False
3            False            False            False            False
4            False            False            False            False

   Condition2_Feedr  Condition2_Norm  Condition2_PosA  Condition2_PosN  \
0             False             True            False            False
1             False             True            False            False
2             False             True            False            False
3             False             True            False            False
4             False             True            False            False

   Condition2_RRAe  Condition2_RRAn  Condition2_RRNn  BldgType_2fmCon  \
0            False            False            False            False
1            False            False            False            False
2            False            False            False            False
3            False            False            False            False
4            False            False            False            False

   BldgType_Duplex  BldgType_Twnhs  BldgType_TwnhsE  HouseStyle_1.5Unf  \
0            False           False            False              False
1            False           False            False              False
2            False           False            False              False
3            False           False            False              False
4            False           False            False              False

   HouseStyle_1Story  HouseStyle_2.5Fin  HouseStyle_2.5Unf  HouseStyle_2Story  \
0              False              False              False               True
1               True              False              False              False
2              False              False              False               True
3              False              False              False               True
4              False              False              False               True

   HouseStyle_SFoyer  HouseStyle_SLvl  RoofStyle_Gable  RoofStyle_Gambrel  \
0              False            False             True              False
1              False            False             True              False
2              False            False             True              False
3              False            False             True              False
4              False            False             True              False

   RoofStyle_Hip  RoofStyle_Mansard  RoofStyle_Shed  RoofMatl_CompShg  \
0          False              False           False              True
1          False              False           False              True
2          False              False           False              True
3          False              False           False              True
4          False              False           False              True

   RoofMatl_Membran  RoofMatl_Metal  RoofMatl_Roll  RoofMatl_Tar&Grv  \
0             False           False          False             False
1             False           False          False             False
2             False           False          False             False
3             False           False          False             False
4             False           False          False             False

   RoofMatl_WdShake  RoofMatl_WdShngl  Exterior1st_AsphShn  \
0             False             False                False
1             False             False                False
2             False             False                False
3             False             False                False
4             False             False                False

   Exterior1st_BrkComm  Exterior1st_BrkFace  Exterior1st_CBlock  \
0                False                False               False
1                False                False               False
2                False                False               False
3                False                False               False
4                False                False               False

   Exterior1st_CemntBd  Exterior1st_HdBoard  Exterior1st_ImStucc  \
0                False                False                False
1                False                False                False
2                False                False                False
3                False                False                False
4                False                False                False

   Exterior1st_MetalSd  Exterior1st_Plywood  Exterior1st_Stone  \
0                False                False              False
1                 True                False              False
2                False                False              False
3                False                False              False
4                False                False              False

   Exterior1st_Stucco  Exterior1st_VinylSd  Exterior1st_Wd Sdng  \
0               False                 True                False
1               False                False                False
2               False                 True                False
3               False                False                 True
4               False                 True                False

   Exterior1st_WdShing  Exterior2nd_AsphShn  Exterior2nd_Brk Cmn  \
0                False                False                False
1                False                False                False
2                False                False                False
3                False                False                False
4                False                False                False

   Exterior2nd_BrkFace  Exterior2nd_CBlock  Exterior2nd_CmentBd  \
0                False               False                False
1                False               False                False
2                False               False                False
3                False               False                False
4                False               False                False

   Exterior2nd_HdBoard  Exterior2nd_ImStucc  Exterior2nd_MetalSd  \
0                False                False                False
1                False                False                 True
2                False                False                False
3                False                False                False
4                False                False                False

   Exterior2nd_Other  Exterior2nd_Plywood  Exterior2nd_Stone  \
0              False                False              False
1              False                False              False
2              False                False              False
3              False                False              False
4              False                False              False

   Exterior2nd_Stucco  Exterior2nd_VinylSd  Exterior2nd_Wd Sdng  \
0               False                 True                False
1               False                False                False
2               False                 True                False
3               False                False                False
4               False                 True                False

   Exterior2nd_Wd Shng  MasVnrType_BrkFace  MasVnrType_None  MasVnrType_Stone  \
0                False                True            False             False
1                False               False             True             False
2                False                True            False             False
3                 True               False             True             False
4                False                True            False             False

   Foundation_CBlock  Foundation_PConc  Foundation_Slab  Foundation_Stone  \
0              False              True            False             False
1               True             False            False             False
2              False              True            False             False
3              False             False            False             False
4              False              True            False             False

   Foundation_Wood  Heating_GasA  Heating_GasW  Heating_Grav  Heating_OthW  \
0            False          True         False         False         False
1            False          True         False         False         False
2            False          True         False         False         False
3            False          True         False         False         False
4            False          True         False         False         False

   Heating_Wall  Electrical_FuseF  Electrical_FuseP  Electrical_Mix  \
0         False             False             False           False
1         False             False             False           False
2         False             False             False           False
3         False             False             False           False
4         False             False             False           False

   Electrical_SBrkr  GarageType_Attchd  GarageType_Basment  \
0              True               True               False
1              True               True               False